### ISSUE TITLE
RuntimeError for pn2_ext.knn_distance

### ISSUE THREAD

**Issue by supriya-gdptl** [tiangeluo/Learning-to-Group#4]
Hello @tiangeluo,

My apologies for bothering you again but, I encountered one error while running the code and need your help to resolve it.

I ran the code to test on PartNet Dataset using the command given in [Test section](https://github.com/tiangeluo/Learning-to-Group#test): `python test_scripts/run_l3.py`. 
However, it gave runtime error while calculating `pn2_ext.knn_distance` for processing `python partnet/test.py --cfg test_configs/l3_bag.yaml`

The following output snippet shows the contents and shape of the two inputs that `pn2_ext.knn_distance` takes i.e. `query_xyz` and `key_xyz`. As you can see the second input i.e. `key_xyz` is an empty array.

```
query_xyz shape:  torch.Size([1, 3, 10000])


key_xyz shape:  torch.Size([1, 3, 0])


query_xyz:  tensor([[[-0.6557,  0.7739, -0.5971,  ..., -0.3986, -0.0142,  0.7362],
         [ 0.6394, -0.6018, -0.6696,  ...,  0.6020,  0.3916,  0.6279],
         [-0.1583,  0.1816,  0.1198,  ...,  0.2410, -0.2675, -0.1770]]],
       device='cuda:0')


key_xyz:  tensor([], device='cuda:0', size=(1, 3, 0))


Traceback (most recent call last):
  File "partnet/test.py", line 528, in <module>
    main()
  File "partnet/test.py", line 525, in main
    test(cfg, output_dir, output_dir_merge, output_dir_save)
  File "partnet/test.py", line 479, in test
    knn_index, _ = _F.knn_distance(invalid_points.unsqueeze(0), valid_points.unsqueeze(0), 5, False)
  File "partnet/../shaper/models/pointnet2/functions.py", line 137, in forward
    index, distance = pn2_ext.knn_distance(query_xyz.contiguous(), key_xyz.contiguous(), num_neighbors)
RuntimeError: The expanded size of the tensor (5) must match the existing size (0) at non-singleton dimension 1.  Target sizes: [10000, 5].  Tensor sizes: [10000, 0] (inferExpandGeometry at /opt/conda/conda-bld/pytorch_1549624239588/work/aten/src/ATen/ExpandUtils.cpp:75)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x45 (0x7f38f4ceccf5 in /python3.5/site-packages/torch/lib/libc10.so)
frame #1: at::inferExpandGeometry(c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>) + 0x898 (0x7f38f54395d8 in /python3.5/site-packages/torch/lib/libcaffe2.so)
frame #2: at::native::expand(at::Tensor const&, c10::ArrayRef<long>, bool) + 0x72 (0x7f38f5634122 in /python3.5/site-packages/torch/lib/libcaffe2.so)
frame #3: at::TypeDefault::expand(at::Tensor const&, c10::ArrayRef<long>, bool) const + 0x16 (0x7f38f57b79c6 in /python3.5/site-packages/torch/lib/libcaffe2.so)
frame #4: torch::autograd::VariableType::expand(at::Tensor const&, c10::ArrayRef<long>, bool) const + 0x43c (0x7f38f2afb8ac in /python3.5/site-packages/torch/lib/libtorch.so.1)
frame #5: at::Tensor::expand(c10::ArrayRef<long>, bool) const + 0x3c (0x7f38f561616c in /python3.5/site-packages/torch/lib/libcaffe2.so)
frame #6: <unknown function> + 0x92d442 (0x7f38f582b442 in /python3.5/site-packages/torch/lib/libcaffe2.so)
frame #7: at::TypeDefault::copy_(at::Tensor&, at::Tensor const&, bool) const + 0x82 (0x7f38f5829642 in /python3.5/site-packages/torch/lib/libcaffe2.so)
frame #8: knn(at::Tensor&, at::Tensor&, int) + 0x764 (0x7f38dde89c74 in partnet/../shaper/models/pointnet2/pn2_ext.cpython-35m-x86_64-linux-gnu.so)
frame #9: <unknown function> + 0x17f13 (0x7f38dde6bf13 in partnet/../shaper/models/pointnet2/pn2_ext.cpython-35m-x86_64-linux-gnu.so)
frame #10: <unknown function> + 0x14655 (0x7f38dde68655 in partnet/../shaper/models/pointnet2/pn2_ext.cpython-35m-x86_64-linux-gnu.so)
<omitting python frames>
frame #17: THPFunction_apply(_object*, _object*) + 0x579 (0x7f391c1dd1e9 in /python3.5/site-packages/torch/lib/libtorch_python.so)
frame #29: __libc_start_main + 0xe7 (0x7f392cfbbb97 in /lib/x86_64-linux-gnu/libc.so.6)

```
Interestingly, when I run the command again, it executed without any error for `l3_bag.yaml` but, gave this error for `l3_hat.yaml` and `l3_trash.yaml`.
Could you please help me resolve this error?

Thank you,
Supriya

**Comment by tiangeluo** [comment]
Thanks for the detailed information! 

The error is caused by a pretrained model fails to be loaded. I've fixed it.
